### ISSUE TITLE
Upgrade server to 0.20

### ISSUE THREAD

**Issue by robb-j** [robb-j/nova-yaml-language-server#20]
This version pulls config which should be better than us having to force it.

**Todos**

- [x] Upgrade server to 0.20
- [x] Get completions working again
- [ ] Pass k8s schema config again

**Comment by robb-j** [comment]
Need to find a new way to pass custom k8s schema configuration to the server now. It can't go in nova config as it is an object which nova doesn't support.

It also isn't offering completion anymore and there is a new unhandled promise rejection warning.

**Comment by robb-j** [comment]
After more investigation is seems the way Server pulls `http` config might be breaking the schemaStore http request. The Server does this request for configuration:

```js
{ section: 'yaml' },
{ section: 'http.proxy' },
{ section: 'http.proxyStrictSSL' },
{ section: '[yaml]' },
```

I can't find anywhere in the LSP spec about dot-notation and nesting keys inside configuration, so I am assuming it is something specific that VSCode does. From Nova it returns:

```js
{ ... },
{},
{},
{ ... }
```

So I assume nova isn't expecting there to be more than one level of indentation via dots.

If I set this configuration via `.nova/Configuration.json`:

```json
"http.proxy": null,
"http.proxyStrictSSL": null
```

That same `workspace/configuration` request returns:

```js
{ ... },
{ 'http.proxy': null },
{ 'http.proxyStrictSSL': null },
{ ... }
```

...which doesn't work either. The server is passing these values to `requests_light` to set the proxy URLs which is failing to `URL.parse` either of the returned values and it is getting to that point because `{}` and `{ 'http.proxy': null }` are truthy.

Looking at the debug logs of VSCode, it is returning this:

```json
[
  "{ ... }",
  "",
  true,
  "{ ... }"
]
```

**Comment by robb-j** [comment]
Related to dot-notation in `workspace/configuration`, I'm not sure what is expected on the value side. It seems that VSCode is expanding dot-notation configuration into full JavaScript objects, e.g.

```json
{
  "format": {
    "enable": false
  }
}
```

Whereas Nova is keeping the dots in the values:

```json
{
  "format.enabled": true
}
```

The Server is expecting expanded JSON and doesn't do anything to expand the dot-notation either, as I have seen `format.enabled` as a key on configuration while debugging the Server.

**Comment by robb-j** [comment]
https://github.com/microsoft/language-server-protocol/issues/972

**Comment by robb-j** [comment]
I've put in a feature request for better contorl of LSP configuration

https://devforum.nova.app/t/workspaceconfiguration-middleware/989

**Comment by robb-j** [comment]
The LanguageServer processes `workspace/didChangeConfiguration` by pulling configuration from the client and doesn't accept the values it passed. The only way to inject Kubernetes mappings now would be to:
- Implement the custom request (which doesn't work in nova)
- Configure the settings passed (Which is in the Nova feature request)

**Comment by robb-j** [comment]
I've put in a custom schema bug report https://devforum.nova.app/t/languageclient-onrequest-isnt-being-called/1064

**Comment by robb-j** [comment]
Fixed in ee762c9
